version: "3.0"

services:
  rest_api:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - APP_PATH=./cmd/api/
    restart: always
    env_file:
      - .env.docker
    networks:
      - backend
    depends_on:
      - postgres
      - redis
    ports:
      - "8088:8088"

  postgres:
    image: postgres:14-alpine
    restart: always
    networks:
      - backend
    environment:
      POSTGRES_DB: echo_rest_api
      # Please update db user in postgres init script 
      POSTGRES_USER: world
      POSTGRES_PASSWORD: hello
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5432:5432"

  kratos:
    image: oryd/kratos:v0.9.0-alpha.3
    networks:
      - backend
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./3rd-parties/kratos
        target: /ory/kratos

  kratos-migrate:
    image: oryd/kratos:v0.9.0-alpha.3
    links:
      - postgres:postgres
    environment:
      - DSN=postgres://world:hello@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    networks:
      - backend
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./3rd-parties/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:latest
    environment:
      - KRATOS_PUBLIC_URL=http://host.docker.internal:8080/ # For connectivity between containers
      - KRATOS_BROWSER_URL=http://127.0.0.1:8080/
      - ORY_SDK_URL=http://kratos:4433
    networks:
      - backend
    depends_on:
      - kratos
    restart: on-failure

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    networks:
      - backend

  redis:
    image: redis:latest
    networks:
      - backend
    ports:
      - "6379:6379"

networks:
  backend:
    driver: bridge