version: "3.7"

services:
  rest_api:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - APP_PATH=./cmd/api/
    restart: always
    env_file:
      - .env.docker
    networks:
      - backend
    depends_on:
      - postgres
      - redis
    ports:
      - "8088:8088"

  postgres:
    image: postgres:13-alpine
    restart: always
    networks:
      - backend
    environment:
      POSTGRES_DB: echo_rest_api
      POSTGRES_USER: world
      POSTGRES_PASSWORD: hello
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    networks:
      - backend
    ports:
      - "6379:6379"

networks:
  backend:
    driver: bridge