name: Go

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    # - uses: harmon758/postgresql-action@v1
    #   with:
    #     postgresql version: '14'
    #     postgresql db: 'test'
    #     postgresql user: 'test'
    #     postgresql password: 'test'

    # - uses: shogo82148/actions-setup-redis@v1
    #   with:
    #     redis-version: "6"

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Download dependencies
      run: go mod tidy

    # - name: Unit test
    #   shell: bash
    #   env:
    #     ## base64 encoded file content: cat .env | base64
    #     ENV_FILE: ${{ secrets.ENV_FILE }}
    #   run: |
    #     echo $ENV_FILE | base64 -d > .env.test
    #     go test -v ./...